-- ============================================================
-- Connect TVC -- five-city expansion, generated by
-- scripts/generate-city-expansion.mjs (re-run for a fresh random batch).
--
-- Adds 25 groups and 50 parties (20
-- solo + 30 two-person couples, 80 people total)
-- spread evenly across five cities -- 5 groups and
-- 10 parties (4 solo, 6 couples) in
-- each of: Flower Mound, Corinth, Coppell, Carrollton, Grapevine.
--
-- PURELY ADDITIVE -- unlike 017_bulk_sample_data_v2.sql, this file
-- contains no DELETEs. It only inserts new rows, continuing the existing
-- id sequence (groups g126-g150, solo parties
-- p201-p220, couple parties
-- cp301-cp330) -- this assumes
-- 017 has already been run with those ids intact and untouched.
--
-- All 25 new group names were checked against the 125
-- group names already in 017_bulk_sample_data_v2.sql and are guaranteed
-- not to collide.
--
-- Match-rate check (new groups vs. new parties only, since all of them
-- share these same 5 cities -- does not cross-check against the existing
-- 125 groups / 500 parties from 017): 40.0% of the new parties
-- have zero candidate groups among the new groups alone, 40.0%
-- have exactly one, 20.0% have two or more (avg 0.88,
-- max 3). Note Corinth and Coppell had zero existing groups/parties
-- before this file, so new households there only match against the
-- 5 new groups in their own city -- expected, not a bug.
--
-- Run this in the Supabase SQL editor any time after 017_bulk_sample_data_v2.sql.
-- ============================================================

insert into public.groups
  (id, name, day, time, area, host, mentor, life, status, format, freq,
   capacity, members, childcare, topic, age_range, start_date, contact_email,
   address, description, placement_details)
values
('g126','The Gonzalezes','Wed','12:00 PM','Flower Mound','Wei Gonzalez and Sydney Gonzalez','—','Everyone','Open','Hybrid','Every other week',16,0,false,'Shared dinner & devotion','30–48','Mar 2017','thegonzalezes@connecttvc.org','6507 Eldorado Pkwy, Flower Mound, TX 75022','A brand-new group, just getting off the ground.','Meets in the host''s living room; enter through the side gate.'),
('g127','The Robertses','Wed','6:00 AM','Flower Mound','Blake Roberts and Gabriela Roberts','Spencer Lang','Couples','New','In-person','Weekly',7,3,true,'Loving our neighbors well','32–48','Nov 2021','therobertses@connecttvc.org','373 Collins St, Flower Mound, TX 75022','One of our longest-running groups — open to absolutely anyone.','A Zoom link goes out to the group same-day for anyone joining online.'),
('g128','The Vances','Tue','6:30 PM','Flower Mound','Jordan Vance and Grace Vance','Elijah Watson','Families','Open','In-person','Weekly',19,0,false,'Marketplace faith & ethics','35–55','Jun 2025','thevances@connecttvc.org','679 Spring Creek Pkwy, Flower Mound, TX 75022','An open, come-as-you-are group perfect for anyone new to the area.','Pets on site (two friendly dogs) — mention if that''s a concern.'),
('g129','The Larsons','Tue','12:00 PM','Flower Mound','Kevin Larson and Michelle Larson','Olivia Brooks','Families','Open','In-person','Every other week',8,4,true,'Singles navigating career and faith','18–24','Jan 2024','thelarsons@connecttvc.org','3734 Spring Creek Pkwy, Flower Mound, TX 75022','One of our longest-running groups — open to absolutely anyone.','Pets on site (two friendly dogs) — mention if that''s a concern.'),
('g130','The Ellisons','Fri','5:00 PM','Flower Mound','Spencer Ellison and Gabriela Ellison','—','Families','Open','In-person','Monthly',23,10,true,'Recovery & redemption stories','22–30','Nov 2026','theellisons@connecttvc.org','9214 Stonebridge Dr, Flower Mound, TX 75022','An open, come-as-you-are group perfect for anyone new to the area.','Driveway parking is tight; street parking is easier.'),
('g131','The Jameses','Tue','12:00 PM','Corinth','Noah James and Karen James','—','Young Adults','Open','In-person','Weekly',19,9,false,'Career & calling','32–48','Apr 2015','thejameses@connecttvc.org','9095 Eldorado Pkwy, Corinth, TX 76210','A new group for couples just starting to build shared habits of faith.','Driveway parking is tight; street parking is easier.'),
('g132','The Thornes','Sat','10:00 AM','Corinth','David Thorne and Ava Thorne','Elizabeth Thorne','Couples','Open','In-person','Weekly',26,20,true,'Bridging seasons of marriage','32–48','Apr 2017','thethornes@connecttvc.org','4447 Belt Line Rd, Corinth, TX 76210','A relaxed gathering where neighbors share a meal and a short devotional.','New members welcome any week, no need to wait for a new term.'),
('g133','The Chapmans','Thu','6:00 PM','Corinth','Kevin Chapman and Ruth Chapman','—','Young Adults','Closed','In-person','Weekly',26,17,true,'Late-night study for grad students','22–30','Jan 2026','thechapmans@connecttvc.org','8325 Eldorado Pkwy, Corinth, TX 76210','Fully virtual and especially welcoming to first-timers.','New members welcome any week, no need to wait for a new term.'),
('g134','The Sinclairs','Wed','5:00 PM','Corinth','David Sinclair and Jessica Sinclair','Dylan Stewart','Everyone','Open','In-person','Monthly',13,11,false,'Marketplace faith & ethics','All ages','Mar 2020','thesinclairs@connecttvc.org','5980 Division St, Corinth, TX 76210','A midday, campus-adjacent gathering for students to connect and recharge.','Meets in the host''s living room; enter through the side gate.'),
('g135','The Wests','Thu','10:00 AM','Corinth','Daniel West and Rachel West','Cody Ramos','Young Adults','Closed','In-person','Monthly',8,4,false,'Marriage & rhythms of faith','35–55','Mar 2025','thewests@connecttvc.org','4381 Precinct Line Rd, Corinth, TX 76210','A new group for couples just starting to build shared habits of faith.','Street parking only — carpooling encouraged.'),
('g136','The Castillos','Tue','12:00 PM','Coppell','Will Castillo and Ella Castillo','Owen Zhang','Students','New','Hybrid','Weekly',22,14,false,'Marriage & rhythms of faith','22–30','Nov 2022','thecastillos@connecttvc.org','7424 Josey Ln, Coppell, TX 75019','Coffee-shop-style mornings, open conversation format.','Meets in the host''s living room; enter through the side gate.'),
('g137','The Wolfes','Wed','6:30 AM','Coppell','Tom Wolfe and Isabela Wolfe','Tom Thompson','Couples','New','In-person','Every other week',24,21,false,'Empty nesters finding purpose','32–48','Jun 2024','thewolfes@connecttvc.org','7955 Eldorado Pkwy, Coppell, TX 75019','A midday, campus-adjacent gathering for students to connect and recharge.','Currently at capacity — check back as spots open.'),
('g138','The Delacroixes','Sun','6:30 PM','Coppell','Kwame Delacroix and Amanda Delacroix','Ruth Griffin','Everyone','Open','In-person','Every other week',18,13,true,'Come-as-you-are community','30–48','Oct 2022','thedelacroixes@connecttvc.org','4293 Spring Creek Pkwy, Coppell, TX 75019','Biweekly conversation focused on strengthening marriages.','Childcare on site; arrive a few minutes early to drop off.'),
('g139','The Larkins','Fri','5:00 PM','Coppell','Robert Larkin and Priya Larkin','—','Everyone','Closed','In-person','Monthly',21,21,false,'Late-night study for grad students','35–55','Sep 2024','thelarkins@connecttvc.org','5658 Eldorado Pkwy, Coppell, TX 75019','A brand-new group, just getting off the ground.','Driveway parking is tight; street parking is easier.'),
('g140','The Ashfords','Wed','6:30 PM','Coppell','Robert Ashford and Kayla Ashford','Sarah Osei','Couples','Open','In-person','Every other week',19,18,false,'Shared dinner & devotion','22–30','Jul 2021','theashfords@connecttvc.org','2946 Timber Creek Dr, Coppell, TX 75019','A relaxed gathering where neighbors share a meal and a short devotional.','Childcare on site; arrive a few minutes early to drop off.'),
('g141','The Prescotts','Wed','5:30 PM','Carrollton','Cody Prescott and Emma Prescott','—','Families','Open','Hybrid','Monthly',20,11,false,'Family life & the Gospels','22–30','May 2024','theprescotts@connecttvc.org','6033 Parker Rd, Carrollton, TX 75006','Coffee-shop-style mornings, open conversation format.','Meets in the campus plaza food court — look for the table tent.'),
('g142','The Kesslers','Thu','6:30 PM','Carrollton','Kwame Kessler and Layla Kessler','Kwame Jones','Everyone','Closed','Online','Monthly',8,3,false,'Bridging seasons of marriage','32–48','Jul 2021','thekesslers@connecttvc.org','1651 Mockingbird Ln, Carrollton, TX 75006','A steady midweek anchor for young adults navigating a new season.','A Zoom link goes out to the group same-day for anyone joining online.'),
('g143','The Walkers','Fri','6:30 AM','Carrollton','Jordan Walker and Mary Walker','Logan Osborne','Families','New','Hybrid','Weekly',9,4,false,'College & career Bible study','18–24','Dec 2024','thewalkers@connecttvc.org','7359 Timber Creek Dr, Carrollton, TX 75006','Practical, honest conversations on parenting with purpose.','Pets on site (two friendly dogs) — mention if that''s a concern.'),
('g144','The Sanchezes','Sat','6:30 AM','Carrollton','Marcus Sanchez and Karen Sanchez','—','Young Adults','Open','In-person','Weekly',12,9,false,'Empty nesters finding purpose','18–24','Sep 2018','thesanchezes@connecttvc.org','1784 Preston Rd, Carrollton, TX 75006','Biweekly conversation focused on strengthening marriages.','Currently at capacity — check back as spots open.'),
('g145','The Longs','Fri','5:30 PM','Carrollton','Spencer Long and Nancy Long','—','Everyone','New','Hybrid','Monthly',8,1,false,'Prayer & scripture memory','All ages','Apr 2015','thelongs@connecttvc.org','2509 Broad St, Carrollton, TX 75006','Weekly gathering with a short devotional for the whole family.','Pets on site (two friendly dogs) — mention if that''s a concern.'),
('g146','The Grahams','Wed','6:00 AM','Grapevine','Hunter Graham and Wei Graham','—','Everyone','Open','Hybrid','Every other week',25,7,false,'Saturday morning conversation','24–32','Dec 2024','thegrahams@connecttvc.org','2285 Main St, Grapevine, TX 76051','Built around whole-family participation, kids welcome.','Pets on site (two friendly dogs) — mention if that''s a concern.'),
('g147','The Marlows','Wed','6:30 AM','Grapevine','Diego Marlow and Ruth Marlow','Luis Thomas','Families','New','Hybrid','Monthly',24,2,true,'Family life & the Gospels','26–40','May 2025','themarlows@connecttvc.org','4859 Main St, Grapevine, TX 76051','A brand-new group, just getting off the ground.','Currently at capacity — check back as spots open.'),
('g148','The Bakers','Tue','5:00 PM','Grapevine','John Baker and Nancy Baker','Victor Ortiz','Couples','Closed','Hybrid','Monthly',14,14,true,'Family life & the Gospels','18–24','Jun 2019','thebakers@connecttvc.org','4817 Meadow Creek Dr, Grapevine, TX 76051','Weekly gathering with a short devotional for the whole family.','Childcare on site; arrive a few minutes early to drop off.'),
('g149','The Freemans','Thu','6:30 PM','Grapevine','Ben Freeman and Hannah Freeman','Layla Cruz','Everyone','Open','Online','Weekly',20,3,true,'Recovery & redemption stories','All ages','Jun 2021','thefreemans@connecttvc.org','8145 Belt Line Rd, Grapevine, TX 76051','A new group for couples just starting to build shared habits of faith.','Text the host by Friday if you need childcare arranged.'),
('g150','The Romeros','Mon','5:30 PM','Grapevine','Dylan Romero and Karen Romero','Sydney Jordan','Students','Closed','In-person','Weekly',10,5,true,'Once-a-month family potluck','30–48','May 2023','theromeros@connecttvc.org','5458 Custer Rd, Grapevine, TX 76051','A relaxed gathering where neighbors share a meal and a short devotional.','Driveway parking is tight; street parking is easier.');

insert into public.parties
  (id, party_name, area, address, age, days, time_pref, life, interests,
   childcare_needed, accessibility, status, group_id, joined, notes)
values
('p201','','Flower Mound','1596 Elm St, Flower Mound, TX 75022',27,ARRAY['Sun','Sat','Wed','Tue']::text[],'Flexible','Young Adults','Sports, community outreach',true,'—','Actively Searching',null,'Mar 2021','Recently married, new to Connect TVC and eager to plug in.'),
('p202','','Flower Mound','3314 Precinct Line Rd, Flower Mound, TX 75022',63,ARRAY['Mon','Sat','Tue','Fri']::text[],'Evenings','Everyone','Coffee, deep conversation',false,'—','Grouped','g129','Jan 2015',''),
('p203','','Flower Mound','2729 Elm St, Flower Mound, TX 75022',38,ARRAY['Sat','Tue','Thu','Wed','Fri']::text[],'Evenings','Families','Running, prayer',false,'—','Actively Searching',null,'Jun 2024','Recently married, new to Connect TVC and eager to plug in.'),
('p204','','Flower Mound','6271 Division St, Flower Mound, TX 75022',26,ARRAY['Thu','Sun','Wed','Sat','Tue','Fri']::text[],'Afternoons','Young Adults','Art, quiet reflection',false,'—','Actively Searching',null,'Mar 2015','Family of four, needs childcare on meeting nights.'),
('cp301','The Phillipses','Flower Mound','3559 Eldorado Pkwy, Flower Mound, TX 75022',42,ARRAY['Fri','Sat','Tue','Wed']::text[],'Evenings','Families','Missions, hospitality',false,'Prefers ground-floor access','Grouped','g128','Apr 2022',''),
('cp302','The Walkers','Flower Mound','1888 Josey Ln, Flower Mound, TX 75022',39,ARRAY['Thu','Wed','Fri','Sat','Tue']::text[],'Evenings','Everyone','Reading, service projects',true,'—','Grouped','g129','Feb 2022','Prefers an early-morning group.'),
('cp303','The Sanderses','Flower Mound','9741 Custer Rd, Flower Mound, TX 75022',20,ARRAY['Fri','Tue','Mon','Wed','Sat']::text[],'Evenings','Students','Missions, hospitality',false,'—','Grouped','g127','Sep 2016','Looking for something close to home.'),
('cp304','The Hernandezes','Flower Mound','8296 FM 407, Flower Mound, TX 75022',41,ARRAY['Wed','Thu','Tue','Fri','Sat']::text[],'Afternoons','Everyone','Running, prayer',true,'—','New',null,'Nov 2015','Sophomore, connected through campus ministry.'),
('cp305','The Rojases','Flower Mound','6118 Main St, Flower Mound, TX 75022',24,ARRAY['Tue','Fri','Thu','Sun']::text[],'Flexible','Young Adults','Reading, service projects',false,'—','Actively Searching',null,'Feb 2017','Long-time member, between groups after a move.'),
('cp306','The Cooks','Flower Mound','3649 Elm St, Flower Mound, TX 75022',36,ARRAY['Thu','Wed','Tue','Mon']::text[],'Afternoons','Everyone','Sports, community outreach',true,'—','Actively Searching',null,'Sep 2020','Looking for something close to home.'),
('p205','','Corinth','5182 Elm St, Corinth, TX 76210',58,ARRAY['Sat','Tue','Fri','Wed','Thu','Sun']::text[],'Afternoons','Everyone','Sports, community outreach',false,'—','Grouped','g135','Sep 2018','New in town, flexible on timing.'),
('p206','','Corinth','5231 Preston Rd, Corinth, TX 76210',48,ARRAY['Tue','Mon','Wed','Fri']::text[],'Mornings','Families','Sports, community outreach',false,'Prefers ground-floor access','Grouped','g131','Feb 2023','Referred by a friend already in a group.'),
('p207','','Corinth','2255 Meadow Creek Dr, Corinth, TX 76210',41,ARRAY['Sat','Thu','Sun','Tue']::text[],'Mornings','Everyone','Running, prayer',false,'—','Grouped','g131','Mar 2017',''),
('p208','','Corinth','8049 Elm St, Corinth, TX 76210',24,ARRAY['Thu','Wed','Fri','Tue','Mon']::text[],'Flexible','Young Adults','Running, prayer',false,'—','Actively Searching',null,'Jun 2017','Family of four, needs childcare on meeting nights.'),
('cp307','The Wests','Corinth','8280 Rufe Snow Dr, Corinth, TX 76210',50,ARRAY['Wed','Thu','Tue','Sat']::text[],'Flexible','Families','Missions, hospitality',false,'—','New',null,'Jan 2017','Family of four, needs childcare on meeting nights.'),
('cp308','The Whitfields','Corinth','9563 Mason Ave, Corinth, TX 76210',65,ARRAY['Wed','Fri','Thu','Tue','Sat']::text[],'Flexible','Everyone','Worship, mentoring',false,'—','New',null,'Dec 2018','New in town, flexible on timing.'),
('cp309','The Youngs','Corinth','3283 Precinct Line Rd, Corinth, TX 76210',37,ARRAY['Fri','Tue','Sun','Thu']::text[],'Mornings','Couples','Hiking, apologetics',true,'—','New',null,'Jul 2018','Referred by a friend already in a group.'),
('cp310','The Martins','Corinth','4762 Meadow Creek Dr, Corinth, TX 76210',42,ARRAY['Thu','Tue','Sat','Wed','Fri']::text[],'Mornings','Families','Worship, mentoring',false,'—','Grouped','g131','Oct 2020','New in town, flexible on timing.'),
('cp311','The Sharmas','Corinth','3818 Mason Ave, Corinth, TX 76210',22,ARRAY['Fri','Wed','Thu','Tue','Sat','Sun']::text[],'Afternoons','Young Adults','Hiking, apologetics',false,'—','Waitlisted',null,'Mar 2021','Referred by a friend already in a group.'),
('cp312','The Browns','Corinth','5128 Josey Ln, Corinth, TX 76210',26,ARRAY['Wed','Tue','Sat','Sun','Mon']::text[],'Mornings','Young Adults','Reading, service projects',false,'—','Actively Searching',null,'Feb 2019','Prefers an early-morning group.'),
('p209','','Coppell','6194 Cross Timbers Rd, Coppell, TX 75019',67,ARRAY['Fri','Tue','Sat','Mon','Thu','Sun']::text[],'Evenings','Everyone','Music, discipleship',false,'—','Waitlisted',null,'Dec 2024','Sophomore, connected through campus ministry.'),
('p210','','Coppell','7529 Mason Ave, Coppell, TX 75019',57,ARRAY['Tue','Wed','Fri','Thu','Sat']::text[],'Evenings','Everyone','Missions, hospitality',false,'—','Grouped','g139','Mar 2021',''),
('p211','','Coppell','8028 Meadow Creek Dr, Coppell, TX 75019',42,ARRAY['Tue','Thu','Wed','Sat','Fri']::text[],'Flexible','Families','Hiking, apologetics',false,'—','Actively Searching',null,'Nov 2018','Referred by a friend already in a group.'),
('p212','','Coppell','2792 Timber Creek Dr, Coppell, TX 75019',61,ARRAY['Tue','Fri','Wed','Thu','Sat','Mon']::text[],'Flexible','Everyone','Reading, service projects',false,'—','Actively Searching',null,'Feb 2017',''),
('cp313','The Smiths','Coppell','2141 Timber Creek Dr, Coppell, TX 75019',41,ARRAY['Thu','Wed','Sun','Sat']::text[],'Mornings','Families','Hiking, apologetics',true,'—','Waitlisted',null,'Apr 2015','Looking for something close to home.'),
('cp314','The Whitcombs','Coppell','7519 Mason Ave, Coppell, TX 75019',48,ARRAY['Wed','Thu','Tue','Sat','Fri']::text[],'Mornings','Everyone','Sports, community outreach',true,'—','Grouped','g137','May 2026','New in town, flexible on timing.'),
('cp315','The Perezes','Coppell','4795 Rufe Snow Dr, Coppell, TX 75019',29,ARRAY['Sat','Mon','Wed','Tue','Fri']::text[],'Mornings','Families','Marriage, serving together',false,'—','Grouped','g136','Sep 2021','Prefers an early-morning group.'),
('cp316','The Simmonses','Coppell','5027 Long Prairie Rd, Coppell, TX 75019',50,ARRAY['Fri','Thu','Tue','Wed','Sat','Sun']::text[],'Evenings','Everyone','Marriage, serving together',false,'—','Actively Searching',null,'Nov 2016','Family of four, needs childcare on meeting nights.'),
('cp317','The Youngs','Coppell','5605 Mason Ave, Coppell, TX 75019',43,ARRAY['Sat','Wed','Thu','Tue','Mon']::text[],'Flexible','Families','Coffee, deep conversation',false,'—','Actively Searching',null,'Sep 2015',''),
('cp318','The Johnsons','Coppell','626 Precinct Line Rd, Coppell, TX 75019',40,ARRAY['Wed','Sat','Mon','Fri','Thu']::text[],'Mornings','Families','Coffee, deep conversation',true,'—','Grouped','g138','May 2019','Sophomore, connected through campus ministry.'),
('p213','','Carrollton','9171 Precinct Line Rd, Carrollton, TX 75006',50,ARRAY['Thu','Sun','Tue','Wed','Mon']::text[],'Evenings','Families','Coffee, deep conversation',false,'—','New',null,'Mar 2017','Looking for something close to home.'),
('p214','','Carrollton','6129 Pioneer Pkwy, Carrollton, TX 75006',52,ARRAY['Tue','Sun','Thu','Wed','Fri','Sat']::text[],'Mornings','Couples','Coffee, deep conversation',true,'—','Grouped','g145','Aug 2022','Looking for something close to home.'),
('p215','','Carrollton','7251 Mason Ave, Carrollton, TX 75006',47,ARRAY['Sat','Fri','Tue','Sun','Wed']::text[],'Afternoons','Everyone','Worship, mentoring',false,'—','Actively Searching',null,'Jan 2018','Recently married, new to Connect TVC and eager to plug in.'),
('p216','','Carrollton','1040 Stonebridge Dr, Carrollton, TX 75006',32,ARRAY['Thu','Fri','Wed','Mon','Sat','Tue']::text[],'Mornings','Young Adults','Missions, hospitality',false,'—','New',null,'Sep 2026','Long-time member, between groups after a move.'),
('cp319','The Parkers','Carrollton','8127 Parker Rd, Carrollton, TX 75006',44,ARRAY['Tue','Wed','Thu','Mon']::text[],'Afternoons','Families','Reading, service projects',false,'—','Grouped','g144','Jan 2017','Prefers an early-morning group.'),
('cp320','The Longs','Carrollton','8730 Parker Rd, Carrollton, TX 75006',46,ARRAY['Tue','Wed','Sat','Mon','Fri']::text[],'Flexible','Couples','Coffee, deep conversation',true,'—','New',null,'Jun 2019','Sophomore, connected through campus ministry.'),
('cp321','The Colemans','Carrollton','1004 Main St, Carrollton, TX 75006',32,ARRAY['Sat','Wed','Mon','Thu','Tue','Fri']::text[],'Evenings','Families','Running, prayer',false,'—','New',null,'May 2016','Referred by a friend already in a group.'),
('cp322','The Jordans','Carrollton','1228 Belt Line Rd, Carrollton, TX 75006',27,ARRAY['Thu','Tue','Fri','Sat']::text[],'Mornings','Young Adults','Reading, service projects',false,'—','Actively Searching',null,'Jun 2020','Recently married, new to Connect TVC and eager to plug in.'),
('cp323','The Bakers','Carrollton','9422 Collins St, Carrollton, TX 75006',18,ARRAY['Sat','Wed','Tue','Fri']::text[],'Afternoons','Students','Parenting, cooking',true,'—','Grouped','g143','Dec 2026','New in town, flexible on timing.'),
('cp324','The Bennetts','Carrollton','6142 Preston Rd, Carrollton, TX 75006',37,ARRAY['Fri','Wed','Mon','Tue','Sat']::text[],'Afternoons','Families','Marriage, serving together',true,'—','Waitlisted',null,'May 2016','Long-time member, between groups after a move.'),
('p217','','Grapevine','9210 Pioneer Pkwy, Grapevine, TX 76051',47,ARRAY['Fri','Sun','Mon','Sat','Thu','Tue']::text[],'Afternoons','Families','Reading, service projects',false,'—','Actively Searching',null,'Jul 2015','Recently married, new to Connect TVC and eager to plug in.'),
('p218','','Grapevine','2596 Belt Line Rd, Grapevine, TX 76051',23,ARRAY['Wed','Mon','Thu','Fri','Tue']::text[],'Evenings','Young Adults','Coffee, deep conversation',true,'—','Grouped','g146','Aug 2024','New in town, flexible on timing.'),
('p219','','Grapevine','4875 Precinct Line Rd, Grapevine, TX 76051',20,ARRAY['Thu','Wed','Fri','Tue','Mon','Sat']::text[],'Mornings','Students','Music, discipleship',false,'—','Grouped','g150','Mar 2019','Prefers an early-morning group.'),
('p220','','Grapevine','9466 Mockingbird Ln, Grapevine, TX 76051',43,ARRAY['Fri','Sat','Wed','Tue','Thu','Sun']::text[],'Mornings','Families','Running, prayer',false,'—','Actively Searching',null,'Oct 2026',''),
('cp325','The Whitakers','Grapevine','4313 Parker Rd, Grapevine, TX 76051',29,ARRAY['Fri','Tue','Sat','Thu']::text[],'Evenings','Everyone','Parenting, cooking',true,'—','Grouped','g147','May 2017',''),
('cp326','The Gonzalezes','Grapevine','3751 Walnut Hill Ln, Grapevine, TX 76051',22,ARRAY['Thu','Wed','Sat','Fri']::text[],'Mornings','Everyone','Hiking, apologetics',true,'—','New',null,'Sep 2016','Family of four, needs childcare on meeting nights.'),
('cp327','The Guerreros','Grapevine','3978 Walnut Hill Ln, Grapevine, TX 76051',67,ARRAY['Sat','Mon','Thu','Tue','Fri','Wed']::text[],'Mornings','Everyone','Worship, mentoring',false,'—','New',null,'Apr 2018','Prefers an early-morning group.'),
('cp328','The Martinezes','Grapevine','5313 Mockingbird Ln, Grapevine, TX 76051',21,ARRAY['Thu','Sun','Fri','Sat','Mon','Wed']::text[],'Afternoons','Students','Hiking, apologetics',false,'—','Actively Searching',null,'Mar 2022','Sophomore, connected through campus ministry.'),
('cp329','The Brookses','Grapevine','908 Custer Rd, Grapevine, TX 76051',42,ARRAY['Wed','Thu','Tue','Fri','Mon','Sat']::text[],'Afternoons','Families','Worship, mentoring',true,'—','Actively Searching',null,'May 2023','Recently married, new to Connect TVC and eager to plug in.'),
('cp330','The Whitsons','Grapevine','5561 FM 407, Grapevine, TX 76051',35,ARRAY['Wed','Thu','Tue','Mon','Sun']::text[],'Evenings','Families','Art, quiet reflection',false,'—','Grouped','g148','Aug 2023','Referred by a friend already in a group.');

insert into public.people
  (id, party_id, name, email, phone)
values
('sp202','p201','Layla Murphy','layla.murphy@email.com','(555) 211-8176'),
('sp203','p202','Rachel Cho','rachel.cho35@email.com','(555) 430-2119'),
('sp204','p203','Monica Griffin','monica.griffin@email.com','(555) 233-7580'),
('sp205','p204','Vanessa Scott','vanessa.scott90@email.com','(555) 328-3487'),
('cp301a','cp301','Diego Phillips','diego.phillips@email.com','(555) 601-4513'),
('cp301b','cp301','Ava Phillips','ava.phillips@email.com','(555) 468-3891'),
('cp302a','cp302','James Walker','james.walker@email.com','(555) 542-3093'),
('cp302b','cp302','Natalie Walker','natalie.walker@email.com','(555) 221-7839'),
('cp303a','cp303','James Sanders','james.sanders@email.com','(555) 352-5615'),
('cp303b','cp303','Susan Sanders','susan.sanders@email.com','(555) 518-7635'),
('cp304a','cp304','David Hernandez','david.hernandez@email.com','(555) 796-6819'),
('cp304b','cp304','Isabela Hernandez','isabela.hernandez@email.com','(555) 900-9747'),
('cp305a','cp305','Isaac Rojas','isaac.rojas@email.com','(555) 418-2120'),
('cp305b','cp305','Rachel Rojas','rachel.rojas@email.com','(555) 964-3629'),
('cp306a','cp306','Tom Cook','tom.cook42@email.com','(555) 850-9259'),
('cp306b','cp306','Layla Cook','layla.cook@email.com','(555) 881-1720'),
('sp206','p205','Daniel Gonzalez','daniel.gonzalez@email.com','(555) 726-3427'),
('sp207','p206','Elizabeth Cox','elizabeth.cox@email.com','(555) 656-3642'),
('sp208','p207','Jessica Ramirez','jessica.ramirez@email.com','(555) 988-7535'),
('sp209','p208','Monica Osborne','monica.osborne34@email.com','(555) 762-2404'),
('cp307a','cp307','Isaac West','isaac.west@email.com','(555) 456-5985'),
('cp307b','cp307','Gabriela West','gabriela.west@email.com','(555) 635-2896'),
('cp308a','cp308','Cody Whitfield','cody.whitfield@email.com','(555) 233-5275'),
('cp308b','cp308','Ruth Whitfield','ruth.whitfield@email.com','(555) 795-1848'),
('cp309a','cp309','Spencer Young','spencer.young83@email.com','(555) 311-8027'),
('cp309b','cp309','Ella Young','ella.young@email.com','(555) 434-8007'),
('cp310a','cp310','Kwame Martin','kwame.martin@email.com','(555) 272-9941'),
('cp310b','cp310','Gabriela Martin','gabriela.martin27@email.com','(555) 384-7914'),
('cp311a','cp311','Gabriel Sharma','gabriel.sharma67@email.com','(555) 852-6831'),
('cp311b','cp311','Layla Sharma','layla.sharma79@email.com','(555) 398-3023'),
('cp312a','cp312','Will Brown','will.brown19@email.com','(555) 638-7784'),
('cp312b','cp312','Nancy Brown','nancy.brown@email.com','(555) 982-8098'),
('sp210','p209','David James','david.james@email.com','(555) 774-9048'),
('sp211','p210','Priya Ellison','priya.ellison88@email.com','(555) 706-8590'),
('sp212','p211','Elijah Ramos','elijah.ramos41@email.com','(555) 270-7018'),
('sp213','p212','Kwame Parker','kwame.parker@email.com','(555) 680-4005'),
('cp313a','cp313','Victor Smith','victor.smith@email.com','(555) 855-7258'),
('cp313b','cp313','Hannah Smith','hannah.smith50@email.com','(555) 372-1203'),
('cp314a','cp314','Hunter Whitcomb','hunter.whitcomb@email.com','(555) 403-3196'),
('cp314b','cp314','Sydney Whitcomb','sydney.whitcomb7@email.com','(555) 615-6594'),
('cp315a','cp315','Ben Perez','ben.perez@email.com','(555) 309-2829'),
('cp315b','cp315','Gabriela Perez','gabriela.perez@email.com','(555) 670-1195'),
('cp316a','cp316','Marcus Simmons','marcus.simmons@email.com','(555) 972-9286'),
('cp316b','cp316','Priya Simmons','priya.simmons34@email.com','(555) 739-3683'),
('cp317a','cp317','Owen Young','owen.young@email.com','(555) 905-8543'),
('cp317b','cp317','Kayla Young','kayla.young21@email.com','(555) 656-1064'),
('cp318a','cp318','Victor Johnson','victor.johnson@email.com','(555) 989-8262'),
('cp318b','cp318','Sydney Johnson','sydney.johnson7@email.com','(555) 297-2777'),
('sp214','p213','David Bailey','david.bailey@email.com','(555) 520-9759'),
('sp215','p214','Priya Chavez','priya.chavez@email.com','(555) 954-1438'),
('sp216','p215','Kwame Jenkins','kwame.jenkins@email.com','(555) 487-1221'),
('sp217','p216','James Whitson','james.whitson@email.com','(555) 238-2734'),
('cp319a','cp319','Tom Parker','tom.parker@email.com','(555) 742-2768'),
('cp319b','cp319','Emma Parker','emma.parker@email.com','(555) 361-5160'),
('cp320a','cp320','Ben Long','ben.long@email.com','(555) 877-4364'),
('cp320b','cp320','Jennifer Long','jennifer.long@email.com','(555) 410-2189'),
('cp321a','cp321','Robert Coleman','robert.coleman@email.com','(555) 948-3739'),
('cp321b','cp321','Sarah Coleman','sarah.coleman90@email.com','(555) 381-6850'),
('cp322a','cp322','Spencer Jordan','spencer.jordan@email.com','(555) 635-3087'),
('cp322b','cp322','Susan Jordan','susan.jordan35@email.com','(555) 930-5270'),
('cp323a','cp323','Dylan Baker','dylan.baker@email.com','(555) 352-5033'),
('cp323b','cp323','Karen Baker','karen.baker@email.com','(555) 664-7108'),
('cp324a','cp324','Logan Bennett','logan.bennett@email.com','(555) 417-6027'),
('cp324b','cp324','Kayla Bennett','kayla.bennett@email.com','(555) 597-1440'),
('sp218','p217','Monica Robinson','monica.robinson@email.com','(555) 787-6194'),
('sp219','p218','Blake Roca','blake.roca36@email.com','(555) 651-5466'),
('sp220','p219','Natalie Torres','natalie.torres@email.com','(555) 304-6922'),
('sp221','p220','Linda Diaz','linda.diaz@email.com','(555) 470-6971'),
('cp325a','cp325','Malik Whitaker','malik.whitaker@email.com','(555) 934-1228'),
('cp325b','cp325','Emma Whitaker','emma.whitaker@email.com','(555) 355-6470'),
('cp326a','cp326','Owen Gonzalez','owen.gonzalez67@email.com','(555) 498-2717'),
('cp326b','cp326','Monica Gonzalez','monica.gonzalez68@email.com','(555) 787-5763'),
('cp327a','cp327','Kwame Guerrero','kwame.guerrero42@email.com','(555) 812-3510'),
('cp327b','cp327','Sarah Guerrero','sarah.guerrero@email.com','(555) 282-4727'),
('cp328a','cp328','David Martinez','david.martinez90@email.com','(555) 837-4943'),
('cp328b','cp328','Susan Martinez','susan.martinez42@email.com','(555) 536-7596'),
('cp329a','cp329','Malik Brooks','malik.brooks@email.com','(555) 368-6381'),
('cp329b','cp329','Karen Brooks','karen.brooks53@email.com','(555) 606-3367'),
('cp330a','cp330','Ben Whitson','ben.whitson@email.com','(555) 233-3236'),
('cp330b','cp330','Ruth Whitson','ruth.whitson@email.com','(555) 904-4002');
